language: node_js

os:
 - linux
 - osx
 - windows

node_js:
  - "node"

git:
  depth: false

addons:
  chrome: stable
  apt:
    packages:
      - xvfb

sudo: required

script:
  - npm run release
  - xvfb-run npm test -- -l chrome
